import { Platform } from 'react-native';

function themedColor(variable: string, lightFallback: string) {
  return Platform.OS === 'web' ? `var(--resq1-${variable}, ${lightFallback})` : lightFallback;
}

export const BrandColors = {
  navy: themedColor('text-strong', '#071A35'),
  deepBlue: themedColor('accent', '#0A376D'),
  blue: themedColor('blue', '#0B74C4'),
  blueBorder: themedColor('blue-border', '#0B74C4'),
  lightBlue: themedColor('info-soft', '#EAF4FF'),
  sky: themedColor('info-border', '#D8ECFF'),
  red: themedColor('red', '#D71920'),
  redSoft: themedColor('red-soft', '#FDECEC'),
  redBorder: themedColor('red-border', '#D71920'),
  redAction: themedColor('red-action', '#D71920'),
  criticalBackground: themedColor('critical-background', '#D71920'),
  criticalBorder: themedColor('critical-border', '#D71920'),
  criticalText: themedColor('critical-text', '#FFFFFF'),
  success: themedColor('success', '#0F766E'),
  successSoft: themedColor('success-soft', '#E8F7F4'),
  successBorder: themedColor('success-border', '#0F766E'),
  warningSoft: themedColor('warning-soft', '#FFF8E5'),
  warning: themedColor('warning', '#B7791F'),
  warningText: themedColor('warning-text', '#7A4B00'),
  warningStrong: themedColor('warning-strong', '#8A4B00'),
  warningEmphasis: themedColor('warning-emphasis', '#B45309'),
  warningBorderStrong: themedColor('warning-border-strong', '#D69E2E'),
  warningAccent: themedColor('warning-accent', '#F59E0B'),
  warningAction: themedColor('warning-action', '#D97706'),
  orangeSoft: themedColor('orange-soft', '#FFF1E6'),
  orange: themedColor('orange', '#EA580C'),
  orangeText: themedColor('orange-text', '#9A3412'),
  dangerText: themedColor('danger-text', '#DC2626'),
  dangerBorder: themedColor('danger-border', '#EF4444'),
  dangerAction: themedColor('danger-action', '#DC2626'),
  cautionSoft: themedColor('caution-soft', '#FFFBE6'),
  dangerSoft: themedColor('danger-soft', '#FEF2F2'),
  neutralSoft: themedColor('neutral-soft', '#EEF2F7'),
  incidentSoft: themedColor('incident-soft', '#E8F1FF'),
  chartSurface: themedColor('chart-surface', '#FAFCFF'),
  border: themedColor('border', '#CBD9E8'),
  muted: themedColor('text-muted', '#5F6F86'),
  subtleText: themedColor('text-subtle', '#5F6F86'),
  text: themedColor('text', '#102033'),
  background: themedColor('background', '#F6F9FC'),
  backgroundSecondary: themedColor('background-secondary', '#F6F9FC'),
  white: themedColor('surface', '#FFFFFF'),
  surface: themedColor('surface', '#FFFFFF'),
  surfaceMuted: themedColor('surface-muted', '#EEF4FA'),
  surfaceElevated: themedColor('surface-elevated', '#FFFFFF'),
  controlSurface: themedColor('control-surface', '#FFFFFF'),
  controlSurfaceSubtle: themedColor('control-surface-subtle', '#F6F9FC'),
  primaryAction: themedColor('primary-action', '#071A35'),
  accentAction: themedColor('accent-action', '#0A376D'),
  primaryMuted: themedColor('primary-muted', '#EAF4FF'),
  navigationActive: themedColor('navigation-active', '#D71920'),
  identitySurface: themedColor('identity-surface', '#071A35'),
  identityBorder: themedColor('identity-border', '#0A376D'),
  onPrimaryMuted: themedColor('on-primary-muted', '#D8ECFF'),
  warningBorder: themedColor('warning-border', '#E7C66C'),
  backdrop: themedColor('backdrop', 'rgba(7, 26, 53, 0.58)'),
  modalBackdrop: themedColor('modal-backdrop', 'rgba(0, 0, 0, 0.5)'),
  dropdownBackdrop: themedColor('dropdown-backdrop', 'rgba(0, 0, 0, 0.4)'),
  placeholder: themedColor('placeholder', '#8B98A9'),
  subtleOverlay: themedColor('subtle-overlay', 'rgba(7, 26, 53, 0.04)'),
  mapOverlay: themedColor('map-overlay', 'rgba(255, 255, 255, 0.95)'),
  routeSafe: themedColor('route-safe', '#22C55E'),
  routeAlternate: themedColor('route-alternate', '#000000'),
  goldAccent: themedColor('gold-accent', '#F7C15C'),
  emergencyOrange: themedColor('emergency-orange', '#FF9500'),
  cardShadow: themedColor('card-shadow', 'rgba(7, 26, 53, 0.08)'),
  splashBlueTop: themedColor('splash-blue-top', '#3C9FFE'),
  splashBlueBottom: themedColor('splash-blue-bottom', '#0274DF'),
  splashBlue: themedColor('splash-blue', '#208AEF'),
  onPrimary: '#FFFFFF',
} as const;
